---
name: eliud_stl_mona_model
description: "eliud_stl_mona is the model for eliud_stl_mona, which is a style which\
  \ can be used for your eliud app. More info at https://eliud.io"
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_stl_mona_model
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  datetime_picker_formfield_new: ^2.1.0
  eliud_core_main: ^1.0.0
  eliud_core_helpers: ^1.0.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  cloud_firestore: ^4.13.5
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.7
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
