---
name: eliud_stl_mona_model
description: eliud_stl_mona is a style which can be used for your eliud app. More
  info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_stl_mona
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  datetime_picker_formfield_new: ^2.1.0                                                              # ANDROID IOS LINUX MACOS WEB WINDOWS

  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
