---
name: eliud_stl_mona_model
description: eliud_stl_mona is a style which can be used for your eliud app. More
  info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_stl_mona
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  delayed_display: ^2.0.0
  eliud_core:
    path: ../eliud_core
  eliud_core_helpers:
    path: ../eliud_core_helpers
  eliud_core_model:
    path: ../eliud_core_model
  eliud_pkg_medium:
    path: ../eliud_pkg_medium
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_colorful_tab: ^0.1.0
  google_fonts: ^6.1.0
  meta: ^1.9.1
  split_view: ^3.2.1
  transparent_image: ^2.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
